### ISSUE TITLE
alerting you to PairAsPipe.jl

### ISSUE THREAD

**Issue by xiaodaigh** [matthieugomez/DataFramesMacros.jl#3]
Seems to have similar design goals

https://github.com/xiaodaigh/PairAsPipe.jl

Although I like the explicit @rows and @cols macro better. 

I will try to contribute to this or similar efforts in DataFramesMeta.jl

**Comment by matthieugomez** [comment]
Similar idea! Your code is really nice — I should look into MacroTools

**Comment by xiaodaigh** [comment]
I have deprecated it in favour of this.
