### ISSUE TITLE
Use symbols rather than variable names 

### ISSUE THREAD

**Issue by eloualiche** [matthieugomez/DataFramesMacros.jl#6]
Could we have a discussion whether it is more appropriate/easier to use symbols rather than  to rely on variable names. 

This would make the package closer to others (see https://github.com/matthieugomez/DataFramesMacros.jl/issues/3 referring to the similar [Pair as Pipe](https://github.com/xiaodaigh/PairAsPipe.jl) package. 

To be clear instead of the current:
```julia
df = DataFrame(x=rand(100))
transform(df, @rows(y = exp(x)))
```

We could have something like:
```julia
transform(df, @rows(:y = exp(:x)))
```

Thoughts?

**Comment by xiaodaigh** [comment]
Personally, I like this approach better. Less typing.

**Comment by eloualiche** [comment]
I suspect the author of the package agrees with you. I have strong opinions but only weak arguments.

I find using symbols makes it a little closer to the `:x => fun => :y` original syntax of DF. I don't want to have to remember which package uses some interpolation and which package actually uses symbols as a standin for the column names. 

@matthieugomez mentions you can also do `x = :name` and then `y = fun($x)` but I find having a syntax such as:
```julia
x = :name
y = fun(x)
```
a little more explicit.

**Comment by matthieugomez** [comment]
Your proposal
```julia
x = :name
y = fun(x)
```
cannot work. The macro does not know whether x refers a real outside variable, or a symbol that actually refers to a column. For instance, DataFramesMeta requires `cols`, e.g. `y = fun(cols(x))`

**Comment by eloualiche** [comment]
I think I am so use to `data.table` that I assume its syntax is easy to emulate. 
I am not sure what happens to parse DT expressions but it looks first for columns then for "out-of-scope" variables. 

I think it's best to wait for 1.0 right now.
