### ISSUE TITLE
Using types inside of rows are misinterpreted as variable names?

### ISSUE THREAD

**Issue by eloualiche** [matthieugomez/DataFramesMacros.jl#7]
I think this could be solved by changing to symbols (see https://github.com/matthieugomez/DataFramesMacros.jl/issues/6)

Parsing the Fama-French daily research factors csv file. I am converting dates to date format using strings. I know there is a better way using only Ints. My point here is somewhere else!

The dataset looks like:
```julia
> df_ff[1:2, :]
2×5 DataFrame
│ Row │ date     │ mktrf    │ smb      │ hml      │ rf       │
│     │ String   │ Float64? │ Float64? │ Float64? │ Float64? │
├─────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ 19260701 │ 0.1      │ -0.24    │ -0.28    │ 0.009    │
│ 2   │ 19260702 │ 0.45     │ -0.32    │ -0.08    │ 0.009    │
```

I want to run the following command:
```julia
> transform!(df_ff, @rows(date = DateTime(parse(Int,date[1:4]), parse(Int,date[5:6]), parse(Int,date[7:8])) ) )
ERROR: ArgumentError: column name :Int not found in the data frame 
```

**Comment by matthieugomez** [comment]
Just to be clear, you can do ^(Int) to avoid it. But yes, any variable is interpreted as the name of a column.

**Comment by eloualiche** [comment]
Just to be clear this is the syntax that is expected:
```julia
> transform!(df_ff, 
  @rows(date = DateTime(parse(^Int,date[1:4]), parse(^Int,date[5:6]), parse(^Int,date[7:8])) ) )
```

What about
```julia
> transform!(df_ff, 
  @rows(:date = DateTime(parse(Int,:date[1:4]), parse(Int,:date[5:6]), parse(Int,:date[7:8])) ) )
```

And we get syntax highlighting for free.
