### ISSUE TITLE
Allow multiple columns

### ISSUE THREAD

**Issue by xiaodaigh** [matthieugomez/DataFramesMacros.jl#9]
Currently,

this is not possible
```
df = transform(df, @cols b = 1 c = 2)
```

but it should be; instead, I need to do this.
```
df = transform(df, @cols(b = 1), @cols(c = 2))
```

**Comment by matthieugomez** [comment]
I was thinking it might a better idea to reserve the multiple args syntax to do stuff like `@cols(r”.x”, mean)` (apply function to multiple arguments). No?

**Comment by xiaodaigh** [comment]
> @cols(r”.x”, mean)

Why wouldn't that be `@cols mean(r".x") y = 1 b = c` and use the macro parsing abilities to pick them out?

**Comment by matthieugomez** [comment]
`mean(r”.x”)` looks like the mean of multiple columns, whereas `cols(mean, r”.x”)` would apply mean separately to multiple column. 

I prefer to restrict `@cols` until I have a better view on how .=> and AsTable are going to be implemented

**Comment by matthieugomez** [comment]
Added. I guess I will use other macro names to do these syntaxes
